version: "3"

services:
  postgis:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=doarpp
      - POSTGRES_USER=devonly
      - POSTGRES_PASSWORD=devonly
    ports:
      - "5432:5432"
